image:
  file: .gitpod.Dockerfile
tasks:
  - before: >
      source ~/.bashrc
    init: |
      echo "Wait for the installation"
      sdkmanager --update
      yes | sdkmanager --licenses
      flutter channel master
      flutter config --enable-web
      flutter doctor -v
      flutter run -d headless-server
      flutter pub get
    command: >
      echo "Ready!"
ports:
  - port: 8080
    onOpen: open-preview
  - port: 5037
    onOpen: ignore
vscode:
  extensions:
    - Dart-Code.dart-code@3.16.0-dev.cloud.2:QwDf9NklkXLz3yA/A5Wsaw==
    - Dart-Code.flutter@3.15.0:2NNVLOcQzPzXP73r8LBOJQ==